set nocompatible              " be iMproved, required
filetype off                  " required

syntax on

colorscheme delek
:set spell spelllang=en_us

:
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'iamcco/mathjax-support-for-mkdp'
Plugin 'iamcco/markdown-preview.vim'
Plugin 'vim-latex/vim-latex'

call vundle#end()            " required
filetype plugin indent on    " required
"filetype plugin on
"K framework 
au BufRead,BufNewFile *.k set filetype=kframework
au! Syntax kframework source kframework.vim
syn on
